package main

import (
	"encoding/json"
	"encoding/xml"
	"fmt"
	"html"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

const generatedKPMHeader = "Generated by MervCode for KPM LSP interoperability. Edit kpm.json/kpm.lock and regenerate instead of hand-editing this file."

type kpmProjectConfig struct {
	Name            string         `json:"name"`
	Group           string         `json:"group"`
	Version         string         `json:"version"`
	SourceDir       string         `json:"sourceDir"`
	TestDir         string         `json:"testDir"`
	Dependencies    map[string]any `json:"dependencies"`
	DevDependencies map[string]any `json:"devDependencies"`
}

// ensureKPMJVMProjectModel exports enough standard JVM project metadata for
// Java/Kotlin language servers to understand a KPM project. KPM is MervCode's
// own project manager, but JDTLS and JetBrains Kotlin LSP natively understand
// Maven/Gradle/Eclipse-style models, not kpm.json directly. For KPM projects
// without an existing Maven/Gradle model we generate deterministic bridge files
// from kpm.json plus the local libs/ cache:
//
//   - settings.gradle.kts / build.gradle.kts for Gradle-aware JVM LSPs
//   - .project / .classpath for JDTLS' Eclipse importer and local jar classpath
//
// Existing Maven/Gradle files are never overwritten: if a project already owns a
// standard build model, that model remains authoritative.
func ensureKPMJVMProjectModel(projectRoot string) error {
	configPath := filepath.Join(projectRoot, "kpm.json")
	if info, err := os.Stat(configPath); err != nil || info.IsDir() {
		return nil
	}

	cfg, err := readKPMProjectConfig(configPath)
	if err != nil {
		return err
	}
	if strings.TrimSpace(cfg.Name) == "" {
		cfg.Name = filepath.Base(projectRoot)
	}
	if strings.TrimSpace(cfg.Version) == "" {
		cfg.Version = "1.0.0"
	}
	if strings.TrimSpace(cfg.SourceDir) == "" {
		cfg.SourceDir = "src"
	}
	if strings.TrimSpace(cfg.TestDir) == "" {
		cfg.TestDir = filepath.ToSlash(filepath.Join(cfg.SourceDir, "test"))
	}

	jars, err := collectKPMJars(projectRoot)
	if err != nil {
		return err
	}

	if !hasAuthoritativeJVMBuild(projectRoot) {
		if err := writeGeneratedKPMFile(filepath.Join(projectRoot, "settings.gradle.kts"), renderKPMSettingsGradle(cfg)); err != nil {
			return err
		}
		if err := writeGeneratedKPMFile(filepath.Join(projectRoot, "build.gradle.kts"), renderKPMBuildGradle(cfg, hasKotlinSources(projectRoot))); err != nil {
			return err
		}
	}

	if err := writeGeneratedKPMFile(filepath.Join(projectRoot, ".project"), renderKPMEclipseProject(cfg)); err != nil {
		return err
	}
	return writeGeneratedKPMFile(filepath.Join(projectRoot, ".classpath"), renderKPMEclipseClasspath(cfg, jars))
}

func readKPMProjectConfig(path string) (kpmProjectConfig, error) {
	var cfg kpmProjectConfig
	data, err := os.ReadFile(path)
	if err != nil {
		return cfg, fmt.Errorf("read KPM config: %w", err)
	}
	if err := json.Unmarshal(data, &cfg); err != nil {
		return cfg, fmt.Errorf("parse KPM config %s: %w", path, err)
	}
	return cfg, nil
}

func hasAuthoritativeJVMBuild(projectRoot string) bool {
	if info, err := os.Stat(filepath.Join(projectRoot, "pom.xml")); err == nil && !info.IsDir() {
		return true
	}
	for _, marker := range []string{"build.gradle", "build.gradle.kts"} {
		path := filepath.Join(projectRoot, marker)
		if info, err := os.Stat(path); err == nil && !info.IsDir() && !isGeneratedKPMFile(path) {
			return true
		}
	}
	return false
}

func writeGeneratedKPMFile(path, content string) error {
	if info, err := os.Stat(path); err == nil && !info.IsDir() && !isGeneratedKPMFile(path) {
		return nil
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write generated KPM LSP file %s: %w", path, err)
	}
	return nil
}

func isGeneratedKPMFile(path string) bool {
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), generatedKPMHeader)
}

func collectKPMJars(projectRoot string) ([]string, error) {
	libsDir := filepath.Join(projectRoot, "libs")
	if info, err := os.Stat(libsDir); err != nil || !info.IsDir() {
		return nil, nil
	}

	var jars []string
	if err := filepath.WalkDir(libsDir, func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || !strings.EqualFold(filepath.Ext(entry.Name()), ".jar") {
			return nil
		}
		rel, err := filepath.Rel(projectRoot, path)
		if err != nil {
			return err
		}
		jars = append(jars, filepath.ToSlash(rel))
		return nil
	}); err != nil {
		return nil, fmt.Errorf("scan KPM libs: %w", err)
	}
	sort.Strings(jars)
	return jars, nil
}

func hasKotlinSources(projectRoot string) bool {
	for _, dir := range []string{
		filepath.Join(projectRoot, "src", "main", "kotlin"),
		filepath.Join(projectRoot, "src", "test", "kotlin"),
	} {
		found := false
		_ = filepath.WalkDir(dir, func(path string, entry fs.DirEntry, err error) error {
			if err != nil || found || entry.IsDir() {
				return nil
			}
			if strings.EqualFold(filepath.Ext(entry.Name()), ".kt") || strings.EqualFold(filepath.Ext(entry.Name()), ".kts") {
				found = true
			}
			return nil
		})
		if found {
			return true
		}
	}
	return false
}

func renderKPMSettingsGradle(cfg kpmProjectConfig) string {
	return fmt.Sprintf("// %s\npluginManagement { repositories { gradlePluginPortal(); mavenCentral() } }\ndependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS); repositories { mavenCentral() } }\nrootProject.name = %q\n", generatedKPMHeader, cfg.Name)
}

func renderKPMBuildGradle(cfg kpmProjectConfig, includeKotlin bool) string {
	var b strings.Builder
	b.WriteString("// " + generatedKPMHeader + "\n")
	b.WriteString("plugins {\n")
	b.WriteString("    java\n")
	if includeKotlin {
		b.WriteString(fmt.Sprintf("    kotlin(\"jvm\") version %q\n", inferKPMKotlinVersion(cfg)))
	}
	b.WriteString("}\n\n")
	if strings.TrimSpace(cfg.Group) != "" {
		b.WriteString(fmt.Sprintf("group = %q\n", cfg.Group))
	}
	b.WriteString(fmt.Sprintf("version = %q\n\n", cfg.Version))
	b.WriteString("repositories { mavenCentral() }\n\n")
	b.WriteString("dependencies {\n")
	b.WriteString("    implementation(fileTree(\"libs\") { include(\"**/*.jar\") })\n")
	b.WriteString("    testImplementation(fileTree(\"libs\") { include(\"**/*.jar\") })\n")
	b.WriteString("}\n")
	return b.String()
}

func inferKPMKotlinVersion(cfg kpmProjectConfig) string {
	for _, deps := range []map[string]any{cfg.Dependencies, cfg.DevDependencies} {
		for coord, spec := range deps {
			if strings.HasPrefix(coord, "org.jetbrains.kotlin:kotlin-stdlib") {
				if version := kpmDependencyVersion(spec); version != "" {
					return version
				}
			}
		}
	}
	return "2.1.21"
}

func kpmDependencyVersion(spec any) string {
	switch v := spec.(type) {
	case string:
		return v
	case map[string]any:
		if raw, ok := v["version"].(string); ok {
			return raw
		}
	}
	return ""
}

func renderKPMEclipseProject(cfg kpmProjectConfig) string {
	type projectDescription struct {
		XMLName   xml.Name `xml:"projectDescription"`
		Name      string   `xml:"name"`
		Comment   string   `xml:"comment"`
		BuildSpec struct {
			BuildCommand struct {
				Name string `xml:"name"`
			} `xml:"buildCommand"`
		} `xml:"buildSpec"`
		Natures struct {
			Nature string `xml:"nature"`
		} `xml:"natures"`
	}

	project := projectDescription{Name: cfg.Name, Comment: generatedKPMHeader}
	project.BuildSpec.BuildCommand.Name = "org.eclipse.jdt.core.javabuilder"
	project.Natures.Nature = "org.eclipse.jdt.core.javanature"
	data, _ := xml.MarshalIndent(project, "", "    ")
	return xml.Header + string(data) + "\n"
}

func renderKPMEclipseClasspath(cfg kpmProjectConfig, jars []string) string {
	var b strings.Builder
	b.WriteString(xml.Header)
	b.WriteString("<!-- " + html.EscapeString(generatedKPMHeader) + " -->\n")
	b.WriteString("<classpath>\n")
	for _, source := range kpmSourceRoots(cfg) {
		b.WriteString(fmt.Sprintf("    <classpathentry kind=\"src\" path=\"%s\"/>\n", html.EscapeString(source)))
	}
	b.WriteString("    <classpathentry kind=\"con\" path=\"org.eclipse.jdt.launching.JRE_CONTAINER\"/>\n")
	for _, jar := range jars {
		b.WriteString(fmt.Sprintf("    <classpathentry kind=\"lib\" path=\"%s\"/>\n", html.EscapeString(jar)))
	}
	b.WriteString("    <classpathentry kind=\"output\" path=\"build/classes/java/main\"/>\n")
	b.WriteString("</classpath>\n")
	return b.String()
}

func kpmSourceRoots(cfg kpmProjectConfig) []string {
	base := filepath.ToSlash(strings.TrimSpace(cfg.SourceDir))
	if base == "" {
		base = "src"
	}
	test := filepath.ToSlash(strings.TrimSpace(cfg.TestDir))
	if test == "" {
		test = filepath.ToSlash(filepath.Join(base, "test"))
	}

	candidates := []string{
		filepath.ToSlash(filepath.Join(base, "main", "java")),
		filepath.ToSlash(filepath.Join(base, "main", "kotlin")),
		filepath.ToSlash(filepath.Join(base, "main", "resources")),
		filepath.ToSlash(filepath.Join(test, "java")),
		filepath.ToSlash(filepath.Join(test, "kotlin")),
		filepath.ToSlash(filepath.Join(test, "resources")),
	}
	seen := make(map[string]bool, len(candidates))
	roots := make([]string, 0, len(candidates))
	for _, candidate := range candidates {
		candidate = strings.Trim(candidate, "/")
		if candidate == "" || seen[candidate] {
			continue
		}
		seen[candidate] = true
		roots = append(roots, candidate)
	}
	return roots
}
