// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FolderDialog():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function LintCode(arg1:string):Promise<Array<main.Diagnostic>>;

export function Quit():Promise<void>;

export function ReadDir(arg1:string):Promise<Array<main.FileItem>>;

export function ReadFile(arg1:string):Promise<string>;
