// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {types} from '../models';

export function AdbDevices():Promise<Array<main.AdbDevice>>;

export function CheckLanguageTools(arg1:string):Promise<main.ToolStatus>;

export function CreateFile(arg1:string):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function CreateLSPSession(arg1:string,arg2:string):Promise<string>;

export function Delete(arg1:string):Promise<void>;

export function DeletePath(arg1:string):Promise<void>;

export function FolderDialog():Promise<string>;

export function FormatDocument(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetLanguageProfile(arg1:string):Promise<main.LanguageProfile>;

export function GitStatus(arg1:string):Promise<types.GitStatusResult>;

export function Greet(arg1:string):Promise<string>;

export function InspectAndReadFile(arg1:string):Promise<types.FileResponse>;

export function InstallTools(arg1:string):Promise<void>;

export function InvalidateWorkspaceCache():Promise<void>;

export function KillLSPServer(arg1:string):Promise<void>;

export function LintDocument(arg1:string,arg2:string,arg3:string):Promise<Array<main.LintDiagnostic>>;

export function ListLSPServers():Promise<Array<main.LSPServerInfo>>;

export function OpenSettingsWindow():Promise<void>;

export function Quit():Promise<void>;

export function ReadDir(arg1:string):Promise<Array<types.FileItem>>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileBytes(arg1:string):Promise<Array<number>>;

export function ReadImageFile(arg1:string):Promise<string>;

export function Rename(arg1:string,arg2:string):Promise<void>;

export function RenamePath(arg1:string,arg2:string):Promise<void>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveFileReference(arg1:string,arg2:string):Promise<main.ResolvedReference>;

export function ResolveProjectRoot(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SearchInWorkspace(arg1:string,arg2:string):Promise<Array<types.SearchMatch>>;

export function StartTerminal(arg1:string,arg2:string):Promise<void>;

export function StartWatcher(arg1:string):Promise<void>;

export function StopAllTerminals():Promise<void>;

export function StopLSPBridge():Promise<void>;

export function StopTerminal(arg1:string):Promise<void>;

export function StopWatcher():Promise<void>;

export function TerminalInput(arg1:string,arg2:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
