// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {types} from '../models';

export function CheckLanguageTools(arg1:string):Promise<main.ToolStatus>;

export function CreateFile(arg1:string):Promise<void>;

export function CreateFolder(arg1:string):Promise<void>;

export function Delete(arg1:string):Promise<void>;

export function DeletePath(arg1:string):Promise<void>;

export function FolderDialog():Promise<string>;

export function FormatDocument(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GitStatus(arg1:string):Promise<types.GitStatusResult>;

export function Greet(arg1:string):Promise<string>;

export function InspectAndReadFile(arg1:string):Promise<types.FileResponse>;

export function InstallTools(arg1:string):Promise<void>;

export function LSPChangeFile(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function LSPCloseFile(arg1:string,arg2:string):Promise<void>;

export function LSPCompletion(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<types.LSPCompletionItem>>;

export function LSPDefinition(arg1:string,arg2:string,arg3:number,arg4:number):Promise<types.LSPLocation>;

export function LSPHover(arg1:string,arg2:string,arg3:number,arg4:number):Promise<types.LSPHoverResult>;

export function LSPOpenFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function LSPReferences(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<types.LSPLocation>>;

export function Quit():Promise<void>;

export function ReadDir(arg1:string):Promise<Array<types.FileItem>>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileBytes(arg1:string):Promise<Array<number>>;

export function ReadImageFile(arg1:string):Promise<string>;

export function Rename(arg1:string,arg2:string):Promise<void>;

export function RenamePath(arg1:string,arg2:string):Promise<void>;

export function SearchInWorkspace(arg1:string,arg2:string):Promise<Array<types.SearchMatch>>;

export function StartWatcher(arg1:string):Promise<void>;

export function StopWatcher():Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
