// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLanguageTools(arg1) {
  return window['go']['main']['App']['CheckLanguageTools'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function FolderDialog() {
  return window['go']['main']['App']['FolderDialog']();
}

export function FormatDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['FormatDocument'](arg1, arg2, arg3);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InspectAndReadFile(arg1) {
  return window['go']['main']['App']['InspectAndReadFile'](arg1);
}

export function InstallTools(arg1) {
  return window['go']['main']['App']['InstallTools'](arg1);
}

export function LSPChangeFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LSPChangeFile'](arg1, arg2, arg3, arg4);
}

export function LSPCloseFile(arg1, arg2) {
  return window['go']['main']['App']['LSPCloseFile'](arg1, arg2);
}

export function LSPCompletion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LSPCompletion'](arg1, arg2, arg3, arg4);
}

export function LSPDefinition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LSPDefinition'](arg1, arg2, arg3, arg4);
}

export function LSPHover(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LSPHover'](arg1, arg2, arg3, arg4);
}

export function LSPOpenFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['LSPOpenFile'](arg1, arg2, arg3);
}

export function LSPReferences(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LSPReferences'](arg1, arg2, arg3, arg4);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileBytes(arg1) {
  return window['go']['main']['App']['ReadFileBytes'](arg1);
}

export function ReadImageFile(arg1) {
  return window['go']['main']['App']['ReadImageFile'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['main']['App']['Rename'](arg1, arg2);
}

export function RenamePath(arg1, arg2) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2);
}

export function SearchInWorkspace(arg1, arg2) {
  return window['go']['main']['App']['SearchInWorkspace'](arg1, arg2);
}

export function StartWatcher(arg1) {
  return window['go']['main']['App']['StartWatcher'](arg1);
}

export function StopWatcher() {
  return window['go']['main']['App']['StopWatcher']();
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
