// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdbDevices() {
  return window['go']['main']['App']['AdbDevices']();
}

export function CheckLanguageTools(arg1) {
  return window['go']['main']['App']['CheckLanguageTools'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['main']['App']['CreateFile'](arg1);
}

export function CreateFolder(arg1) {
  return window['go']['main']['App']['CreateFolder'](arg1);
}

export function CreateLSPSession(arg1, arg2) {
  return window['go']['main']['App']['CreateLSPSession'](arg1, arg2);
}

export function Delete(arg1) {
  return window['go']['main']['App']['Delete'](arg1);
}

export function DeletePath(arg1) {
  return window['go']['main']['App']['DeletePath'](arg1);
}

export function FolderDialog() {
  return window['go']['main']['App']['FolderDialog']();
}

export function FormatDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['FormatDocument'](arg1, arg2, arg3);
}

export function GitStatus(arg1) {
  return window['go']['main']['App']['GitStatus'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InspectAndReadFile(arg1) {
  return window['go']['main']['App']['InspectAndReadFile'](arg1);
}

export function InstallTools(arg1) {
  return window['go']['main']['App']['InstallTools'](arg1);
}

export function OpenSettingsWindow() {
  return window['go']['main']['App']['OpenSettingsWindow']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileBytes(arg1) {
  return window['go']['main']['App']['ReadFileBytes'](arg1);
}

export function ReadImageFile(arg1) {
  return window['go']['main']['App']['ReadImageFile'](arg1);
}

export function Rename(arg1, arg2) {
  return window['go']['main']['App']['Rename'](arg1, arg2);
}

export function RenamePath(arg1, arg2) {
  return window['go']['main']['App']['RenamePath'](arg1, arg2);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SearchInWorkspace(arg1, arg2) {
  return window['go']['main']['App']['SearchInWorkspace'](arg1, arg2);
}

export function StartTerminal(arg1, arg2) {
  return window['go']['main']['App']['StartTerminal'](arg1, arg2);
}

export function StartWatcher(arg1) {
  return window['go']['main']['App']['StartWatcher'](arg1);
}

export function StopAllTerminals() {
  return window['go']['main']['App']['StopAllTerminals']();
}

export function StopLSPBridge() {
  return window['go']['main']['App']['StopLSPBridge']();
}

export function StopTerminal(arg1) {
  return window['go']['main']['App']['StopTerminal'](arg1);
}

export function StopWatcher() {
  return window['go']['main']['App']['StopWatcher']();
}

export function TerminalInput(arg1, arg2) {
  return window['go']['main']['App']['TerminalInput'](arg1, arg2);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
