// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FolderDialog() {
  return window['go']['main']['App']['FolderDialog']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function LintCode(arg1) {
  return window['go']['main']['App']['LintCode'](arg1);
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ReadDir(arg1) {
  return window['go']['main']['App']['ReadDir'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}
